#!/bin/bash
me=hom
debug=
for i in /media/hom/EXAM*; do 
    mountpoint=/media/${me}/casper-rw-$(basename ${i}) 
    ${debug} mkdir ${mountpoint}
    ${debug} mount -o loop ${i}/casper-rw  ${mountpoint}
    subdir=$(basename ${i})
    if [ -e  ${mountpoint}/exam/exam ]; then
	${debug} mkdir -p ${subdir}
	cp -r ${mountpoint}/exam/exam ${subdir}/exam
	echo found exam in ${i}
    fi
done
wait
sync
for i in /media/hom/EXAM*; do 
    mountpoint=/media/${me}/casper-rw-$(basename ${i}) 
    ${debug} umount ${mountpoint}
    ${debug} rmdir ${mountpoint}
done
sync
for i in /media/hom/EXAM*; do 
    umount ${i}
done
